// ============================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated from: data/at_3gpp.yaml
// Content hash (SHA-256 of entries section only): 4e62d380af5971be
// Generator: scripts/generate_headers.py
// Generator version: 1.0.0
// YAML schema version: 1.0.0
// Database version: 1.0.0
// To regenerate: cmake --build . --target generate
// ============================================================

#pragma once
#include "persistence_types.hpp"
#include "database_version.hpp"
#include <array>
#include <cstddef>
#include <string_view>

namespace sim800::persistence::at_3gpp {

inline constexpr std::array<PersistenceEntry, 11> AT_3GPP_PERSISTENCE = {{
    PersistenceEntry{
        "AT+CCWA",
        "n",
        PROFILE_UNSET,
        Category::At3gpp27007,
        PersistenceMode::ExplicitSave,
        "AT&W",
        SaveScope::BothProfiles,
        std::string_view{},
        PowerLossBehavior::Retained,
        ResetBehavior::ResetToProfile,
        FactoryResetBehavior::ResetToFactoryDefault,
        false,
        false,
        false,
        "SIM800 Series_AT Command Manual_V1.12.pdf",
        "Chapter 3, Section AT+CCWA",
        ExtractionStatus::NotSpecified,
        PresenceStatus::Present,
        "V1.12",
        std::array<std::string_view, MAX_AVAILABLE_VERSIONS>{{
            "V1.01",
            "V1.10",
            "V1.12",
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
        }},
        3,
        std::array<VersionEntry, MAX_VERSION_SPECIFIC>{{
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        }},
        0,
        90,
        "Call waiting control; inferred from AT command manual."
    },
    PersistenceEntry{
        "AT+CGREG",
        "n",
        PROFILE_UNSET,
        Category::At3gpp27007,
        PersistenceMode::ExplicitSave,
        "AT&W",
        SaveScope::BothProfiles,
        std::string_view{},
        PowerLossBehavior::Retained,
        ResetBehavior::ResetToProfile,
        FactoryResetBehavior::ResetToFactoryDefault,
        false,
        false,
        false,
        "SIM800 Series_AT Command Manual_V1.12.pdf",
        "Chapter 3, Section AT+CGREG",
        ExtractionStatus::ExtractedFromText,
        PresenceStatus::Present,
        "V1.12",
        std::array<std::string_view, MAX_AVAILABLE_VERSIONS>{{
            "V1.01",
            "V1.10",
            "V1.12",
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
        }},
        3,
        std::array<VersionEntry, MAX_VERSION_SPECIFIC>{{
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        }},
        0,
        80,
        "GPRS network registration status configuration."
    },
    PersistenceEntry{
        "AT+CLIP",
        "n",
        PROFILE_UNSET,
        Category::At3gpp27007,
        PersistenceMode::ExplicitSave,
        "AT&W",
        SaveScope::BothProfiles,
        std::string_view{},
        PowerLossBehavior::Retained,
        ResetBehavior::ResetToProfile,
        FactoryResetBehavior::ResetToFactoryDefault,
        false,
        false,
        false,
        "SIM800 Series_AT Command Manual_V1.12.pdf",
        "Chapter 3, Section AT+CLIP",
        ExtractionStatus::NotSpecified,
        PresenceStatus::Present,
        "V1.12",
        std::array<std::string_view, MAX_AVAILABLE_VERSIONS>{{
            "V1.01",
            "V1.10",
            "V1.12",
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
        }},
        3,
        std::array<VersionEntry, MAX_VERSION_SPECIFIC>{{
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        }},
        0,
        88,
        "Calling line identification; inferred from AT command manual."
    },
    PersistenceEntry{
        "AT+CLIR",
        "n",
        PROFILE_UNSET,
        Category::At3gpp27007,
        PersistenceMode::ExplicitSave,
        "AT&W",
        SaveScope::BothProfiles,
        std::string_view{},
        PowerLossBehavior::Retained,
        ResetBehavior::ResetToProfile,
        FactoryResetBehavior::ResetToFactoryDefault,
        false,
        false,
        false,
        "SIM800 Series_AT Command Manual_V1.12.pdf",
        "Chapter 3, Section AT+CLIR",
        ExtractionStatus::NotSpecified,
        PresenceStatus::Present,
        "V1.12",
        std::array<std::string_view, MAX_AVAILABLE_VERSIONS>{{
            "V1.01",
            "V1.10",
            "V1.12",
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
        }},
        3,
        std::array<VersionEntry, MAX_VERSION_SPECIFIC>{{
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        }},
        0,
        89,
        "Calling line identification restriction; inferred from AT command manual."
    },
    PersistenceEntry{
        "AT+COLP",
        "n",
        PROFILE_UNSET,
        Category::At3gpp27007,
        PersistenceMode::ExplicitSave,
        "AT&W",
        SaveScope::BothProfiles,
        std::string_view{},
        PowerLossBehavior::Retained,
        ResetBehavior::ResetToProfile,
        FactoryResetBehavior::ResetToFactoryDefault,
        false,
        false,
        false,
        "SIM800 Series_AT Command Manual_V1.12.pdf",
        "Chapter 3, Section AT+COLP",
        ExtractionStatus::NotSpecified,
        PresenceStatus::Present,
        "V1.12",
        std::array<std::string_view, MAX_AVAILABLE_VERSIONS>{{
            "V1.01",
            "V1.10",
            "V1.12",
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
        }},
        3,
        std::array<VersionEntry, MAX_VERSION_SPECIFIC>{{
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        }},
        0,
        92,
        "Connected line identification presentation; inferred from AT command manual."
    },
    PersistenceEntry{
        "AT+CPBS",
        "storage",
        PROFILE_UNSET,
        Category::At3gpp27007,
        PersistenceMode::ExplicitSave,
        "AT&W",
        SaveScope::BothProfiles,
        std::string_view{},
        PowerLossBehavior::Retained,
        ResetBehavior::ResetToProfile,
        FactoryResetBehavior::ResetToFactoryDefault,
        false,
        false,
        false,
        "SIM800 Series_AT Command Manual_V1.12.pdf",
        "Chapter 3, Section AT+CPBS",
        ExtractionStatus::NotSpecified,
        PresenceStatus::Present,
        "V1.12",
        std::array<std::string_view, MAX_AVAILABLE_VERSIONS>{{
            "V1.01",
            "V1.10",
            "V1.12",
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
        }},
        3,
        std::array<VersionEntry, MAX_VERSION_SPECIFIC>{{
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        }},
        0,
        100,
        "Phonebook storage selection; inferred from AT command manual."
    },
    PersistenceEntry{
        "AT+CPMS",
        "mem1",
        PROFILE_UNSET,
        Category::At3gpp27005,
        PersistenceMode::ExplicitSave,
        "AT&W",
        SaveScope::BothProfiles,
        std::string_view{},
        PowerLossBehavior::Retained,
        ResetBehavior::ResetToProfile,
        FactoryResetBehavior::ResetToFactoryDefault,
        false,
        false,
        false,
        "SIM800 Series_AT Command Manual_V1.12.pdf",
        "Chapter 4, Section AT+CPMS",
        ExtractionStatus::ExtractedFromText,
        PresenceStatus::Present,
        "V1.12",
        std::array<std::string_view, MAX_AVAILABLE_VERSIONS>{{
            "V1.01",
            "V1.10",
            "V1.12",
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
        }},
        3,
        std::array<VersionEntry, MAX_VERSION_SPECIFIC>{{
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        }},
        0,
        110,
        "Preferred message storage selection."
    },
    PersistenceEntry{
        "AT+CPOL",
        "index",
        PROFILE_UNSET,
        Category::At3gpp27007,
        PersistenceMode::ExplicitSave,
        "AT&W",
        SaveScope::BothProfiles,
        std::string_view{},
        PowerLossBehavior::Retained,
        ResetBehavior::ResetToProfile,
        FactoryResetBehavior::ResetToFactoryDefault,
        false,
        false,
        false,
        "SIM800 Series_AT Command Manual_V1.12.pdf",
        "Chapter 3, Section AT+CPOL",
        ExtractionStatus::NotSpecified,
        PresenceStatus::Present,
        "V1.12",
        std::array<std::string_view, MAX_AVAILABLE_VERSIONS>{{
            "V1.01",
            "V1.10",
            "V1.12",
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
        }},
        3,
        std::array<VersionEntry, MAX_VERSION_SPECIFIC>{{
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        }},
        0,
        105,
        "Preferred operator list; inferred from AT command manual."
    },
    PersistenceEntry{
        "AT+CREG",
        "n",
        PROFILE_UNSET,
        Category::At3gpp27007,
        PersistenceMode::ExplicitSave,
        "AT&W",
        SaveScope::BothProfiles,
        std::string_view{},
        PowerLossBehavior::Retained,
        ResetBehavior::ResetToProfile,
        FactoryResetBehavior::ResetToFactoryDefault,
        false,
        false,
        false,
        "SIM800 Series_AT Command Manual_V1.12.pdf",
        "Chapter 3, Section AT+CREG",
        ExtractionStatus::ExtractedFromText,
        PresenceStatus::Present,
        "V1.12",
        std::array<std::string_view, MAX_AVAILABLE_VERSIONS>{{
            "V1.01",
            "V1.10",
            "V1.12",
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
        }},
        3,
        std::array<VersionEntry, MAX_VERSION_SPECIFIC>{{
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        }},
        0,
        75,
        "Network registration unsolicited result code configuration."
    },
    PersistenceEntry{
        "AT+CSSN",
        "n",
        PROFILE_UNSET,
        Category::At3gpp27007,
        PersistenceMode::ExplicitSave,
        "AT&W",
        SaveScope::BothProfiles,
        std::string_view{},
        PowerLossBehavior::Retained,
        ResetBehavior::ResetToProfile,
        FactoryResetBehavior::ResetToFactoryDefault,
        false,
        false,
        false,
        "SIM800 Series_AT Command Manual_V1.12.pdf",
        "Chapter 3, Section AT+CSSN",
        ExtractionStatus::NotSpecified,
        PresenceStatus::Present,
        "V1.12",
        std::array<std::string_view, MAX_AVAILABLE_VERSIONS>{{
            "V1.01",
            "V1.10",
            "V1.12",
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
        }},
        3,
        std::array<VersionEntry, MAX_VERSION_SPECIFIC>{{
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        }},
        0,
        95,
        "Supplementary service notifications; inferred from AT command manual."
    },
    PersistenceEntry{
        "AT+CUSD",
        "n",
        PROFILE_UNSET,
        Category::At3gpp27007,
        PersistenceMode::ExplicitSave,
        "AT&W",
        SaveScope::BothProfiles,
        std::string_view{},
        PowerLossBehavior::Retained,
        ResetBehavior::ResetToProfile,
        FactoryResetBehavior::ResetToFactoryDefault,
        false,
        false,
        false,
        "SIM800 Series_AT Command Manual_V1.12.pdf",
        "Chapter 3, Section AT+CUSD",
        ExtractionStatus::NotSpecified,
        PresenceStatus::Present,
        "V1.12",
        std::array<std::string_view, MAX_AVAILABLE_VERSIONS>{{
            "V1.01",
            "V1.10",
            "V1.12",
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
            std::string_view{},
        }},
        3,
        std::array<VersionEntry, MAX_VERSION_SPECIFIC>{{
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        VERSION_ENTRY_PAD,
        }},
        0,
        96,
        "Unstructured supplementary service data; inferred from AT command manual."
    },
}};

inline constexpr std::size_t AT_3GPP_PERSISTENCE_COUNT = AT_3GPP_PERSISTENCE.size();
static_assert(AT_3GPP_PERSISTENCE_COUNT <= MAX_PERSISTENCE_PER_HEADER,
              "AT_3GPP_PERSISTENCE count exceeds MAX_PERSISTENCE_PER_HEADER");

inline const PersistenceEntry* find_at_3gpp_persistence(std::string_view command,
                                                         std::string_view param_name,
                                                         std::uint8_t profile_number = PROFILE_UNSET) noexcept {
    for (std::size_t i = 0; i < AT_3GPP_PERSISTENCE_COUNT; ++i) {
        if (AT_3GPP_PERSISTENCE[i].command == command
            && AT_3GPP_PERSISTENCE[i].parameter_name == param_name
            && AT_3GPP_PERSISTENCE[i].profile_number == profile_number) {
            return &AT_3GPP_PERSISTENCE[i];
        }
    }
    return nullptr;
}

} // namespace sim800::persistence::at_3gpp
